services:
  frontend:
    build: ../src/frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ../src/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_USER: app_user
      DATABASE_PASSWORD: app_password

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ../init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: