services:
  frontend:
    build: ../src/frontend
    image: davisdre/resume-frontend:latest
    container_name: resume-frontend
    ports:
      - "80:8080"
    depends_on:
      - backend

  backend:
    build: ../src/backend
    image: davisdre/resume-backend:latest
    container_name: resume-backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_USER: "resume_user"
      DATABASE_PASSWORD: "db_password"

  db:
    image: mariadb:latest
    container_name: resume-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_DATABASE: "visitor_counter"
      MYSQL_USER: "resume_user"
      MYSQL_PASSWORD: "db_password"
    ports:
      - "3306:3306"
    healthcheck: 
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"] 
      start_period: 10s
      interval: 10s 
      timeout: 5s 
      retries: 3
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: