# Dockerfile for Frontend
FROM nginx:1-alpine-slim

COPY index.html /usr/share/nginx/html/index.html
COPY css /usr/share/nginx/html/css
COPY js /usr/share/nginx/html/js
COPY images /usr/share/nginx/html/images
COPY favicon-200x200.png /usr/share/nginx/html/favicon-200x200.png
COPY site.webmanifest /usr/share/nginx/html/site.webmanifest